# CMake targets
Targets, executables, binaries, c++ standards and more. In this document we will explore the several targets we can setup with your cmake project.

:toc:
:sectnums:

== Introduction
Once you decide the target you want to build through CMake, you can also set (different manners) standard for the target to be used.

```cmake
set(CXX_STANDARD_REQUIRED ON) # Make C++20 a hard requirement
set(CMAKE_CXX_STANDARD 20) # Default C++ standard for the target
```

=== CXX_STANDARD_REQUIRED
This variable is added in version 3.1. That is a boolean describing whether the value of the CXX_STANDARD is a requirement. 

If this property is `OFF` or unset, the CXX_STANDARD target property is treated as optional and may "decay" to a previous standard if the requested isn't available. For compilers that have no notion of a standard level, such as MSVC 1800 (Visual studio 2013) and lower, this has no effect.

==== CXX_STANDARD
The C++ standard whose features are requested to build this target.

This property specifies the C++ standard whose features are requested to build this target. For some compilers, this results in adding a flag such as `-std=gnu++11` to the compile line.

For compilers that have no notion of a standard level, such as Microsoft Visual C++ before 2015 Update 3, this has no effect.

===== Values
Here are the supported values for the variable:

. 98 (C++98)
. 11 (C++11)
. 14 (C++14)

====== Added in Version 3.8

. 17 (C++17)

====== Added in Version 3.12

. 20 (C++20)

====== Added in Version 3.20

. 23 (C++23)

====== Added in Version 3.25

. 26 (C++26)

If the value requested foes not result in a compile flag being added for the compiler in use, a previous standard flag will be added instead. This means that using:

=======
set_property(TARGET tgt PROPERTY CXX_STANDARD 11)
=======
With a compiler which does not support `--std=gnu++11` or an equivalent gloag will not result in an error or warning, but will instead add the `--std=gnu++98` flag if supported. This "decay" behavior may be controlled with the `CXX_STANDARD_REQUIRED` target property. Additionally the `CXX_EXTENSIONS` target property may be used to control whether compiler-specific extensions are enabled on a per-target basis.

=== CXX_EXTENSIONS
Added in version 3.1.

This variable is a boolean that is specifying whether the compiler specific extensions are requested.

This property specifies whether compiler specific extensions should be used. For some compilers, this results in adding a flag such as `-src=gnu++11` instead of `-std=c++11` to the compile time.

This property is `ON` by default. The basic C++ standard level is controlled by the `CXX_STANDARD` target property.

This property is initialized by the value of the `CMAKE_CXX_EXTENSIONS` vairable if set when a target is created and otherwise by the value of `CMAKE_EXTENSIONS_DEFAULT`.

=== CMAKE_CXX_STANDARD
The value for the `CMAKE_CXX_STANDARD` set the value for the `CXX_STANDARD` target property, if it is set when the target is created.

We can specify all the variable defined above (such as `CMAKE_CXX_STANDARD` or `CXX_EXTENSIONS` or `CXX_STANDARD_REQUIRED`) on a larger scope by using the `set` command, or specifying them using the `target_compile_features` like so:

======
target_compile_features(operations PUBLIC cxx_std_20)
======

The call to `target_compile_features` specify above will set the c++ standard to use C++20. This will only be used by the target named `operations`.

== Work on targets
Actually, we saw how to create one and only one individual target. Although CMake is used for making Cross-platform build to compile and use your project in several OS (Linux, Windows, Mac), you can also:

. Setting up static libraries
. Setting up embedded libraries
. Setting up separated libraries
. Building individual target
. C++ standard at different granularities

=== Build an individual target
Something that you can do is create an individual target, an individual application as a single target, that is made by making use of the following command:

======
add_executable(<binary> <sources_files>)
======

Using this add_executable, all the given <sources_files> in that command will be put in one place, making the executable.

=== Attach properties
Although you succeed in showing to `CMake` where to find the source file, what if about the headers one ? Actually itsn't written in the `add_executable`, still it is mandatory to tell `CMake` about it.

==== target_include_directory
Using the following command:
======
target_include_directories(<binary> <PUBLIC|PRIVATE> <include_path>)
======
CMake will know where to look for the header file that you are using in your project.

==== target_compile_feature
Using the following command:
======
target_compile_feature(<binary> <PUBLIC|PRIVATE|INTERFACE> <feature>)
======
You will be able to specify feature for the compiler to put on. This is required when compiling a given target (in our case, target being the <binary>). If the feature isn't listed in the `CMAKE_C_COMPILE_FEATURES`, `CMAKE_CUDA_COMPILE_FEATURES`, or `CMAKE_CXX_COMPILE_FEATURES` variables, then an error will be reported by `CMake`.

In case of the feature needin an additionnal compiler flag, such as `-std=gnu++11`, this flag will be added automatically.

The `INTERFACE`, `PUBLIC` and `PRIVATE` are required to specify the scope of the features. `PRIVATE` and `PUBLIC` items will populate the `COMPILE_FEATURES` property of `<target>`, `PUBLIC` and `INTERFACE` itels will populate the `INTERFACE_COMPILE_FEATURES` property of `<target>`. Repeated calls for the same `<target>` append items.

=== Target executable
Sometimes, you will need to build software that is using definitions, for example
```cpp
#include <iostream>
#include <string>

int main() {
    # ifdef AWESOME
        std::string message = "YOU ARE AWESOME!\n";
    # else
        std::string message = "YOU ARE HUGLY!\n";
    #endif
    std::cout << message << std::endl;
    return 0;
}
```
The code above is using the `AWESOME` definition. If we provide to the compiler the `AWESOME` definition, the final application will print `YOU ARE AWESOME`, otherwise it will print `YOU ARE HUGLY`. 

How can we give to the target (the binary) this `AWESOME` attribute ? In order to dos so, we will take use of the `target_compile_definitions` like this:

======
target_compile_definition(<binary> <PUBLIC|PRIVATE|INTERFACE> <DEFINITION>)
======

In our case, the `DEFINITION` part of the `target_compile_definition` is going to be `AWESOME`.

So in this case, if you are using `add_executable` you will have an executable being the target, although it's not the only type:

=== Target library
Library is another very popular target you can do with your CMake. However, there are several types of libraries we can do in your C++ project such as:

. Static libraries
. Dynamics libraries

==== libraries
A library is code designed to be reused by other programs. It is made of one or more human-readable header files that contain the declaration of variables, functions, classes and other programming elements that the library provides. The actual implementation lies in a precompiled binary, distributed along with the headers.

==== Static libraries
A static library is simply a collection of binary objects archived into a single file, usually with a `.a` extension on Unix-like system and `.lib` on Windows. A static library gets merged by the linker into the final executable during the linking stage.

More specifically, the linker copies all the elements marked as undefined by  the compiler from the library into the executable file. 

Static libraries are good for portability: Your program contains everything it needs in a single executable file, which is easier to distribute and install for the end user. On the other hand, the program grows bigger. Historically libraries could only be static.

==== Dynamics libraries
A dynamic library (also known as shared library) is a slightly more complexe creature. It contains binary data like a static library and had a `.so` extension on Linux, `.dylib` on `iOS` and `.dll` on Windows. 

A dynamic library is designed to be _linked_ to the main executable, rather than being merged into it. 

The linker creatres a special connection between functions and variables used in the main executable and their actual implementations provided by the dynamic library. 

This way multipls programs can reference to the same library without the need for each to have its own copy.

===== Usage

Using dynamic libraries results in a smaller final executable, as it doesn't contain the actual library code. 

Also, if the library is updated, all programs that link to it will instantly benefit. 

Conversely, a program that uses static libraries needs to be recompiled every time a new version of the library is published, in order to merge the changes into the final executable.

This is an important property when it comes to security; bugfixes in a synamic library will automatically propagate to all programs that link to it, with no need to recompile. Unfortunately this mechanism makes the whole program more susceptible to breaking: what if the library changes in a way that is no longer usable by the executable ?

== Create library
While you are creating your `CMakeLists.txt` you can create several targets (that can be either executable, libraries, ...), you will be able to create this target also.

```cmake
add_library(<name> <STATIC|DYNAMIC> <source_files>)
target_include_directories(<name> <PUBLIC|PRIVATE|INTERFACE> <folder_include>)
target_compile_features(<name> <PUBLIC|PRIVATE|INTERFACE> <options>)

...
```
Listing the 3 first lines above, this is enough to create a static library using CMake. However, you create the library, now you'll need to link it to your executable:
```cmake
...
add_executable(<name> <source_files>)
...
target_link_libraries(<name> <PUBLIC|PRIVATE|INTERFACE> <library_name>)
```
=== target_link_libraries
Specify the libraries or glags to use when linking a given target and / or its dependents. From linked library targets will be propagated. Usage requirements of a target's depenencies affect compilation of its own source.

==== Usage
In order to use `target_link_libraries`, you can do for instance, the following:

```cmake
# Library
set(TARGET_LIBRARY operations)
add_library(${TARGET_LIBRARY} STATIC operations/src/operations.cpp)
target_include_directories(${TARGET_LIBRARY} PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/operations/include)
target_compile_features(${TARGET_LIBRARY} PUBLIC cxx_std_20)

# Target
set(TARGET_NAME HelloBinary)
file(
    ...
)

add_executable(${TARGET_NAME} ${SRC_FILES})
target_compile_features(${TARGET_NAME} PRIVATE cxx_std_20)
target_include_directories( ... )
target_link_libraries(${TARGET_NAME} PUBLIC ${TARGET_LIBRARY})
```

===== Library
In the above `CMake` code, you first specify the library using the command `add_library`. Once that's done, we'll add it to the executable through the `target_link_libraries` command.

This way, you'll be able to create and link a static library into your target.

Using this system above, this can let you manage file easily in your `C++` project.

=== Self contained static libraries
Although the above technique works, it's not the only way to do so, some peoples like to setup completely separate libraries and put them in a separate folder.

==== Library and dependence
When you create a static / dynamic libraries through CMake, all the `target_include_directories` of each library you are creating are going to be given to the executable that depends on the library.

And all the paragraph above is true in case of the scope you create in the `target_include_directories` of the library. You can either specify `PUBLIC`, `PRIVATE` and `INTERFACE`, if you specify `PUBLIC` you'll be able to load the include without including directly into the executable.

== Specifying your standard
Using `CMake` you will be able to specify the standard of your build on specific way:

=== Specify on target level
You can compile using the specific standard on a target level using the following command:

======
target_compile_features(<target> <PRIVATE|PUBLIC|INTERFACE> <features>...)
======

Using the `target_compile_features` you will be able to specify the standard on the given target when compiling it. If the feature isn't listed in the `CMAKE_C_COMPILE_FEATURES`, `CMAKE_CUDA_COMPILE_FEATURES` or even `CMAKE_CXX_COMPILE_FEATURES` variables, then an error will be reported by `CMake`.

If the use of the feature requirezs an additional compiler lag, such as `-sed=gnu++11`, the given flag will be added automatically.

=== Specify the standard in a global level
One way you can do such thing is by making use of a `CMake` variable. Such as:

```cmake
set(CXX_STANDARD_REQUIRED ON) # CMake C++20 a hard requirement
set(CMAKE_CXX_STANDARD 20) # Default C++ standard for targets
```

You can (as we didi above) make use of the `set` command in order to initialize the cmake variable.

==== CXX_STANDARD_REQUIRED
This variable is a boolean variable that specify either the standard is required or not.

By default the variable `CXX_STANDARD_REQUIRED` is `OFF`, and if you want it on, you can do such:

======
set(CXX_STANDARD_REQUIRED ON)
======

Using this command, you'll be able to say to `CMake` that the stadard you will specify is about to be required for the target you specify into.

==== CMAKE_CXX_STANDARD
This variable is a default value for the `CXX_STANDARD` target property, if set when a target is created.

If you take the 2 variables specified above, you should be sure that the compiler that `CMake` is using has the standard you specified onto both of the variable defined above.

To conclude about this standard for the compilation, we should be able to either put it on a local target by using the command named `target_compile_features(<target> <PUBLIC|PRIVATE|INTERFACE> cxx_std_xx)`

This command will set the standard to the `<targets>` and if you want to specify on a global scope, you can make use of some cmake variable defined above.

=== Building targets selectively
If you are having a CMakeLists.txt with different targets setups, you can choose the target you have to build.

Inside of the project, there is several target inside of this CMakeLists.txt file. However, maybe you don't want to compile the library often as you would with the executable, so you could use the following:

```bash
cmake -G <build_name> -S <sources> 
```

Using the above command, you'll be able to create a project using cmake with the generator you choose, by making use of the CMake CLI:

```bash
cmake --build . --target <target_name>
```

======
Using CMake, that will let you the posssibility to generate not only the build of the project, but also create only one target inside of your CMakeLists.txt if you have several.
======
